<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <LangVersion>12.0</LangVersion>
    <Version>6.0.5</Version>
    <Copyright>© 2020-2024 Johnson Controls</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetasysServices\MetasysServices.csproj" />
  </ItemGroup>

</Project>
